# Blueprint realizzato da domoticafacile.it per l'integrazione Raccolta Rifiuti.
blueprint:
  name: Annuncio raccolta rifiuti con Google Home
  description: >
    Annuncia cosa verrà raccolto domani, ogni sera a uno o due orari specificati,
    usando Google Home.
  domain: automation
  input:
    sensore_raccolta:
      name: Sensore raccolta rifiuti
      selector:
        entity:
          domain: sensor
    dispositivo_google:
      name: Dispositivo Google (media_player)
      selector:
        entity:
          domain: media_player
    orario_annuncio_1:
      name: Primo orario dell'annuncio
      selector:
        time: {}
      default: "20:00:00"
    abilita_secondo_orario:
      name: Abilita secondo orario
      selector:
        boolean: {}
      default: false
    orario_annuncio_2:
      name: Secondo orario dell'annuncio
      selector:
        time: {}
      default: "20:30:00"
    volume_pre_annuncio:
      name: Volume prima dell'annuncio
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.05
          mode: slider
      default: 0.6
    volume_post_annuncio:
      name: Volume dopo l'annuncio
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.05
          mode: slider
      default: 0.3

trigger:
  - platform: time
    at: !input orario_annuncio_1
    id: primo_annuncio
  - platform: time
    at: !input orario_annuncio_2
    id: secondo_annuncio

variables:
  sensore: !input sensore_raccolta
  secondario_attivo: !input abilita_secondo_orario

condition:
  - condition: template
    value_template: >
      {{ (state_attr(sensore, 'collection_types') or []) | length > 0 }}
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ trigger.id == 'primo_annuncio' }}"
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ trigger.id == 'secondo_annuncio' }}"
          - condition: template
            value_template: "{{ secondario_attivo }}"

action:
  - variables:
      raccolta: "{{ state_attr(sensore, 'collection_types') or [] }}"
      tipi: >
        {% if raccolta | length > 1 %}
          {{ raccolta[:-1] | join(', ') }} e {{ raccolta[-1] }}
        {% elif raccolta | length == 1 %}
          {{ raccolta[0] }}
        {% else %}
          nessun tipo di rifiuto definito
        {% endif %}
      messaggio: "Domani verrà raccolto: {{ tipi }}."

  - service: media_player.volume_set
    data:
      entity_id: !input dispositivo_google
      volume_level: !input volume_pre_annuncio

  - service: tts.google_translate_say
    data:
      entity_id: !input dispositivo_google
      message: "{{ messaggio }}"

  - delay: 5

  - service: media_player.volume_set
    data:
      entity_id: !input dispositivo_google
      volume_level: !input volume_post_annuncio

mode: single
