# Blueprint realizzato da domoticafacile.it per l'integrazione Raccolta Rifiuti.
blueprint:
  name: Annuncio raccolta rifiuti con Alexa
  description: >
    Annuncia cosa verrà raccolto domani, ogni sera a uno o due orari specificati,
    usando Alexa.
  domain: automation
  input:
    sensore_raccolta:
      name: Sensore raccolta rifiuti
      selector:
        entity:
          domain: sensor
    dispositivo_alexa:
      name: Dispositivo Alexa (media_player)
      selector:
        entity:
          domain: media_player
    orario_annuncio_1:
      name: Primo orario dell'annuncio
      selector:
        time: {}
      default: "20:00:00"
    abilita_secondo_orario:
      name: Abilita secondo orario
      selector:
        boolean: {}
      default: false
    orario_annuncio_2:
      name: Secondo orario dell'annuncio
      selector:
        time: {}
      default: "20:30:00"
    abilita_controllo_presenza:
      name: Controllo presenza
      selector:
        boolean: {}
      default: false
    dispositivo_presenza_1:
      name: Primo telefono (facoltativo)
      selector:
        entity:
          domain: device_tracker
      default: ""
    dispositivo_presenza_2:
      name: Secondo telefono (facoltativo)
      selector:
        entity:
          domain: device_tracker
      default: ""

trigger:
  - platform: time
    at: !input orario_annuncio_1
  - platform: time
    at: !input orario_annuncio_2
    id: secondo_annuncio

variables:
  sensore: !input sensore_raccolta
  secondario_attivo: !input abilita_secondo_orario
  controllo_presenza_attivo: !input abilita_controllo_presenza
  tracker_1: !input dispositivo_presenza_1
  tracker_2: !input dispositivo_presenza_2

condition:
  - condition: template
    value_template: >
      {{ (state_attr(sensore, 'collection_types') or []) | length > 0 }}
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ trigger.id != 'secondo_annuncio' }}"
      - condition: template
        value_template: "{{ trigger.id == 'secondo_annuncio' and secondario_attivo }}"
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ not controllo_presenza_attivo }}"
      - condition: template
        value_template: >
          {{
            (tracker_1 in states and is_state(tracker_1, 'home')) or
            (tracker_2 in states and is_state(tracker_2, 'home'))
          }}

action:
  - variables:
      raccolta: "{{ state_attr(sensore, 'collection_types') or [] }}"
      tipi: "{{ raccolta | join(', ') if raccolta else 'nessun tipo di rifiuto definito' }}"
      messaggio: "Domani verrà raccolto: {{ tipi }}."
  - service: notify.alexa_media
    data:
      target:
        - !input dispositivo_alexa
      message: "{{ messaggio }}"
      data:
        type: announce
        method: speak

mode: single
