# blueprint realizzato da domoticafacile.it per l'integrazione Raccolta Rifiuti.
blueprint:
  name: Annuncio raccolta rifiuti con Google Home
  description: >
    Annuncia cosa verrà raccolto domani, ogni sera a uno o due orari specificati,
    usando Google Home.
  domain: automation
  input:
    calendario_raccolta:
      name: Calendario raccolta rifiuti
      selector:
        entity:
          domain: calendar
    dispositivo_google:
      name: Dispositivo Google (media_player)
      selector:
        entity:
          domain: media_player
    orario_annuncio_1:
      name: Primo orario dell'annuncio
      selector:
        time: {}
      default: "20:00:00"
    abilita_secondo_orario:
      name: Abilita secondo orario
      description: Attiva questa opzione per impostare un secondo orario di annuncio
      default: false
      selector:
        boolean: {}
    orario_annuncio_2:
      name: Secondo orario dell'annuncio
      selector:
        time: {}
      default: "20:30:00"
    volume_pre_annuncio:
      name: Volume prima dell'annuncio
      description: Imposta il volume (da 0.0 a 1.0)
      default: 0.6
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.05
          mode: slider
    volume_post_annuncio:
      name: Volume dopo l'annuncio
      description: Imposta il volume da ripristinare (da 0.0 a 1.0)
      default: 0.3
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.05
          mode: slider
    abilita_controllo_presenza:
      name: Controllo presenza
      description: Esegui solo se almeno uno dei due telefoni è in casa
      default: false
      selector:
        boolean: {}
    dispositivo_presenza_1:
      name: Primo telefono da controllare (device_tracker)
      selector:
        entity:
          domain: device_tracker
    dispositivo_presenza_2:
      name: Secondo telefono da controllare (device_tracker)
      selector:
        entity:
          domain: device_tracker

trigger:
  - platform: time
    at: !input orario_annuncio_1
  - platform: time
    at: !input orario_annuncio_2
    id: secondo_annuncio

variables:
  cal: !input calendario_raccolta
  secondario_attivo: !input abilita_secondo_orario
  controllo_presenza_attivo: !input abilita_controllo_presenza
  tracker_1: !input dispositivo_presenza_1
  tracker_2: !input dispositivo_presenza_2

condition:
  - condition: state
    entity_id: !input calendario_raccolta
    state: "on"
  - condition: template
    value_template: >
      {{ (state_attr(cal, 'message') or '') | trim != '' }}
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ trigger.id != 'secondo_annuncio' }}"
      - condition: template
        value_template: "{{ trigger.id == 'secondo_annuncio' and secondario_attivo }}"
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ not controllo_presenza_attivo }}"
      - condition: template
        value_template: >
          {{ is_state(tracker_1, 'home') or is_state(tracker_2, 'home') }}

action:
  - variables:
      eventi: "{{ state_attr(cal, 'message') }}"
  - service: media_player.volume_set
    data:
      entity_id: !input dispositivo_google
      volume_level: !input volume_pre_annuncio
  - service: tts.google_translate_say
    data:
      entity_id: !input dispositivo_google
      message: "Domani verrà raccolto: {{ eventi }}."
  - delay: 5
  - service: media_player.volume_set
    data:
      entity_id: !input dispositivo_google
      volume_level: !input volume_post_annuncio

mode: single
